version: "3.8"

services:
  frontend:
    image: handa-web-user
    pull_policy: never
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_ENV=local
        - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
        - NEXT_PUBLIC_FRONTEND_URL=${NEXT_PUBLIC_FRONTEND_URL}
    container_name: handa-web-user
    restart: always
    ports:
      - 8089:8089

networks:
  quivr-network:
    driver: bridge
